### ISSUE TITLE
Typical runtime?

### ISSUE THREAD

**Issue by margaretwoodhouse** [baoxingsong/dCNS#13]
Hi there:

I'm wondering what the typical runtime of cut1Gap should be (using default parameters, and the default CISDISTANCE of 100000 from sequenceUpStreamGeneAndDownStreamV2.py to get flanking sequence)? I'm doing sorghum against B73 and I've been running 91222 jobs in parallel for about 26 hours now, and it's only about a third of the way done. Is that typical?

Thanks so much!

**Comment by baoxingsong** [comment]
Yes, that is the setting I used.
I ran 80 jobs in parallel for about 1 week.
Since dCNS aligns everything using the sensitive approach, it is slower than k-mer triggered seed-and-extend approach.
As well, dCNS used a standard dynamic approach (not the banded one), the memory cost for each job may be very large. Some jobs may be killed due to out-of-memory. The checkUnfinishedJobsV2.pl script is to identify which jobs were killed and then you could rerun them by running fewer jobs in parallel.

**Comment by margaretwoodhouse** [comment]
Ok great, thanks so much. That's very helpful.
