### ISSUE TITLE
How to remove "N" both in ref genome and query genome?

### ISSUE THREAD

**Issue by StuYuXu** [baoxingsong/dCNS#18]
Hi~

I just used your software to get a sam file. Now, I want to remove "N" and get the real match for CNSs. However, I met some questions.

1. If both ref and query genome contain Ns like this. The cigar of this situation is 5 match or not.
REF ATNAT
que ATNAT

2. Why so much frequent "Ns" in the sam file? Why not to stop alignment when meet Ns?

3. What's the penalty when meet "Ns" in alignment?

So, these are my questions. Thank you!

**Comment by baoxingsong** [comment]
Since we performed genome hard masking, we masked high frequency and CDS, that is where those 'N's come from.
1) The cigar would be 2 matches, 1 insertion, 1 deletion and 2 matches.
2) We remove those Ns from sequences for sequence alignment. The input sequences for alignment do not have Ns. After sequence alignment, we put those Ns back to the sequence.
3) Please see answer 2.
Please read the fig. 1 of the manuscript, that plot may explain your questions better.

**Comment by StuYuXu** [comment]
Thanks for your answer. I think I understand the tool better now. Just as an example:

>1       16      1       1227897 134     80705780H6M4D5M258D258I25M1I6M1D14M1D10M1I22M5I18M 


the match in bed file in my opinion is:

1	1227896	1227902	1	80705779	80705785
1	1227906	1227911	1	80705785	80705790
1	1228169	1228194	1	80706048	80706073
1	1228194	1228200	1	80706074	80706080
1	1228201	1228215	1	80706080	80706094
1	1228216	1228226	1	80706094	80706104
1	1228226	1228248	1	80706105	80706127
1	1228248	1228266	1	80706132	80706150

Does this bed file correct? In the original sequence alignment, the masked sequences were removed, so that can cause these eight coordinates combined to a larger sequence.

After that, the larger sequence was broken into eight pieces because Ns were put back to the sequence. Am I right to understand the princle and output for your tool?

Does that also mean the masked region could ( like high frequency sequence)  break the CNSs? Because the lager CNS was found in a continuous way, but was broken by these masked regions.

Thank you~

**Comment by baoxingsong** [comment]
https://github.com/baoxingsong/dCNS/issues/16

**Comment by StuYuXu** [comment]
I got it. Thanks~
